export const AI_PROVIDERS = [
  {
    name: "xAI",
    models: [
      { name: "grok-2-1212", multimodal: false },
      { name: "grok-2-vision-1212", multimodal: true },
      { name: "grok-beta", multimodal: false },
      { name: "grok-vision-beta", multimodal: true },
    ],
  },
  {
    name: "OpenAI",
    models: [
      { name: "gpt-4o", multimodal: true },
      { name: "gpt-4o-mini", multimodal: true },
      { name: "gpt-4o-audio-preview", multimodal: false },
      { name: "gpt-4-turbo", multimodal: true },
      { name: "gpt-4", multimodal: false },
      { name: "gpt-3.5-turbo", multimodal: false },
      { name: "o1", multimodal: true },
      { name: "o1-mini", multimodal: true },
      { name: "o1-preview", multimodal: false },
      { name: "o3-mini", multimodal: false },
      { name: "chatgpt-4o-latest", multimodal: true },
    ],
  },

  {
    name: "Anthropic",
    models: [
      { name: "claude-3-7-sonnet-20250219", multimodal: true },
      { name: "claude-3-5-sonnet-20241022", multimodal: true },
      { name: "claude-3-5-sonnet-20240620", multimodal: true },
      { name: "claude-3-5-haiku-20241022", multimodal: false },
      { name: "claude-3-opus-20240229", multimodal: true },
      { name: "claude-3-sonnet-20240229", multimodal: true },
      { name: "claude-3-haiku-20240307", multimodal: true },
    ],
  },
  {
    name: "Amazon Bedrock",
    models: [
      { name: "amazon.titan-tg1-large", multimodal: false },
      { name: "amazon.titan-text-express-v1", multimodal: false },
      { name: "amazon.nova-micro-v1:0	", multimodal: false },
      { name: "amazon.nova-lite-v1:0", multimodal: true },
      { name: "amazon.nova-pro-v1:0", multimodal: true },
      { name: "anthropic.claude-3-7-sonnet-20250219-v1:0", multimodal: true },
      { name: "anthropic.claude-3-5-sonnet-20241022-v2:0", multimodal: true },
      { name: "anthropic.claude-3-5-sonnet-20240620-v1:0", multimodal: true },
      { name: "anthropic.claude-3-5-haiku-20241022-v1:0", multimodal: false },
      { name: "anthropic.claude-3-opus-20240229-v1:0", multimodal: true },
      { name: "anthropic.claude-3-sonnet-20240229-v1:0", multimodal: true },
      { name: "anthropic.claude-3-haiku-20240307-v1:0", multimodal: true },
      { name: "anthropic.claude-v2:1", multimodal: false },
      { name: "cohere.command-r-v1:0", multimodal: false },
      { name: "cohere.command-r-plus-v1:0", multimodal: false },
      { name: "deepseek.r1-v1:0", multimodal: false },
      { name: "meta.llama2-13b-chat-v1", multimodal: false },
      { name: "meta.llama2-70b-chat-v1", multimodal: false },
      { name: "meta.llama3-8b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-70b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-1-8b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-1-70b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-1-405b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-2-1b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-2-3b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-2-11b-instruct-v1:0", multimodal: false },
      { name: "meta.llama3-2-90b-instruct-v1:0", multimodal: false },
      { name: "mistral.mistral-7b-instruct-v0:2", multimodal: false },
      { name: "mistral.mixtral-8x7b-instruct-v0:1", multimodal: false },
      { name: "mistral.mistral-large-2402-v1:0", multimodal: false },
      { name: "mistral.mistral-small-2402-v1:0", multimodal: false },
    ],
  },
  {
    name: "Google Generative AI",
    models: [
      { name: "gemini-2.5-pro-exp-03-25", multimodal: true },
      { name: "gemini-2.0-flash-001", multimodal: true },
      { name: "gemini-1.5-pro", multimodal: true },
      { name: "gemini-1.5-pro-latest", multimodal: true },
      { name: "gemini-1.5-flash", multimodal: true },
      { name: "gemini-1.5-flash-latest", multimodal: true },
      { name: "gemini-1.5-flash-8b", multimodal: true },
      { name: "gemini-1.5-flash-8b-latest", multimodal: true },
    ],
  },
  {
    name: "Google Vertex",
    models: [
      { name: "gemini-2.0-flash-001", multimodal: true },
      { name: "gemini-2.0-flash-exp", multimodal: true },
      { name: "gemini-1.5-flash", multimodal: true },
      { name: "gemini-1.5-pro", multimodal: true },
    ],
  },
  {
    name: "Mistral",
    models: [
      { name: "pixtral-large-latest", multimodal: true },
      { name: "mistral-large-latest", multimodal: false },
      { name: "mistral-small-latest", multimodal: false },
      { name: "ministral-3b-latest", multimodal: false },
      { name: "ministral-8b-latest", multimodal: false },
      { name: "pixtral-12b-2409", multimodal: true },
    ],
  },
  {
    name: "Together.ai",
    models: [
      {
        name: "meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo",
        multimodal: true,
      },
      {
        name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
        multimodal: true,
      },
      { name: "mistralai/Mixtral-8x22B-Instruct-v0.1", multimodal: false },
      { name: "mistralai/Mistral-7B-Instruct-v0.3", multimodal: false },
      { name: "deepseek-ai/DeepSeek-V3", multimodal: false },
      { name: "google/gemma-2b-it", multimodal: false },
      { name: "Qwen/Qwen2.5-72B-Instruct-Turbo", multimodal: false },
      { name: "databricks/dbrx-instruct", multimodal: false },
    ],
  },
  {
    name: "Cohere",
    models: [
      { name: "command-a-03-2025", multimodal: false },
      { name: "command-r-plus", multimodal: false },
      { name: "command-r", multimodal: false },
      { name: "command-a-03-2025", multimodal: false },
      { name: "command", multimodal: false },
      { name: "command-light", multimodal: false },
    ],
  },
  {
    name: "Fireworks",
    models: [
      { name: "accounts/fireworks/models/deepseek-r1", multimodal: false },
      { name: "accounts/fireworks/models/deepseek-v3", multimodal: false },
      {
        name: "accounts/fireworks/models/llama-v3p1-405b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/llama-v3p1-8b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/llama-v3p2-3b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/mixtral-8x7b-instruct-hf",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/mixtral-8x22b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/qwen2p5-coder-32b-instruct",
        multimodal: false,
      },
      {
        name: "accounts/fireworks/models/llama-v3p2-11b-vision-instruct",
        multimodal: true,
      },
      { name: "accounts/fireworks/models/yi-large", multimodal: false },
    ],
  },
  {
    name: "DeepInfra",
    models: [
      { name: "meta-llama/Llama-3.3-70B-Instruct-Turbo", multimodal: false },
      { name: "meta-llama/Llama-3.3-70B-Instruct", multimodal: false },
      { name: "meta-llama/Meta-Llama-3.1-405B-Instruct", multimodal: false },
      {
        name: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
        multimodal: false,
      },
      { name: "meta-llama/Meta-Llama-3.1-70B-Instruct", multimodal: false },
      {
        name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
        multimodal: false,
      },
      { name: "meta-llama/Meta-Llama-3.1-8B-Instruct", multimodal: false },
      { name: "meta-llama/Llama-3.2-11B-Vision-Instruct", multimodal: true },
      { name: "meta-llama/Llama-3.2-90B-Vision-Instruct", multimodal: true },
      { name: "mistralai/Mixtral-8x7B-Instruct-v0.1", multimodal: false },
      { name: "deepseek-ai/DeepSeek-V3", multimodal: false },
      { name: "deepseek-ai/DeepSeek-R1", multimodal: false },
      {
        name: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        multimodal: false,
      },
      { name: "deepseek-ai/DeepSeek-R1-Turbo", multimodal: false },
      { name: "nvidia/Llama-3.1-Nemotron-70B-Instruct", multimodal: false },
      { name: "Qwen/Qwen2-7B-Instruct", multimodal: false },
      { name: "Qwen/Qwen2.5-72B-Instruct", multimodal: false },
      { name: "Qwen/Qwen2.5-Coder-32B-Instruct", multimodal: false },
      { name: "Qwen/QwQ-32B-Preview", multimodal: false },
      { name: "google/codegemma-7b-it", multimodal: false },
      { name: "google/gemma-2-9b-it", multimodal: false },
      { name: "microsoft/WizardLM-2-8x22B", multimodal: false },
    ],
  },
  {
    name: "DeepSeek",
    models: [
      { name: "deepseek-chat", multimodal: false },
      { name: "deepseek-reasoner", multimodal: false },
    ],
  },
  {
    name: "Cerebras",
    models: [
      { name: "llama3.1-8b", multimodal: false },
      { name: "llama3.1-70b", multimodal: false },
      { name: "llama3.3-70b", multimodal: false },
    ],
  },
  {
    name: "Groq",
    models: [
      { name: "gemma2-9b-it", multimodal: false },
      { name: "llama-3.3-70b-versatile", multimodal: false },
      { name: "llama-3.1-8b-instant", multimodal: false },
      { name: "llama-guard-3-8b", multimodal: false },
      { name: "llama3-70b-8192", multimodal: false },
      { name: "llama3-8b-8192", multimodal: false },
      { name: "mixtral-8x7b-32768", multimodal: false },
      { name: "qwen-qwq-32b", multimodal: false },
      { name: "mistral-saba-24b", multimodal: false },
      { name: "qwen-2.5-32b", multimodal: false },
      { name: "deepseek-r1-distill-qwen-32b", multimodal: false },
      { name: "deepseek-r1-distill-llama-70b", multimodal: false },
    ],
  },
  {
    name: "Perplexity",
    models: [
      { name: "sonar-pro", multimodal: false },
      { name: "sonar", multimodal: false },
    ],
  },
];
